# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revcat < Formula
  desc "The RevenueCat CLI"
  homepage "https://github.com/akshitkrnagpal/revcat"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.1.1/revcat_0.1.1_darwin_amd64.tar.gz"
      sha256 "6f1ee31d9abb7e42fa19c54609af799add3f42ceb938fca0c212ee4db0bd0b11"

      define_method(:install) do
        bin.install "revcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.1.1/revcat_0.1.1_darwin_arm64.tar.gz"
      sha256 "278cc6321c0ee1384a4cfa3b5c1f3969d52382064e10b421d547077f95bf0f4e"

      define_method(:install) do
        bin.install "revcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.1.1/revcat_0.1.1_linux_amd64.tar.gz"
      sha256 "9e049d8a9b57b49be5e88f3668f0c09127dcf8770afca042a0d1d2a6cc9599c9"
      define_method(:install) do
        bin.install "revcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.1.1/revcat_0.1.1_linux_arm64.tar.gz"
      sha256 "23141f39619e334b230904bdaa6993c47e7c68c5c7210f3df1d3275dd49a1f83"
      define_method(:install) do
        bin.install "revcat"
      end
    end
  end

  test do
    system "#{bin}/revcat", "version"
  end
end
