# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revcat < Formula
  desc "The RevenueCat CLI"
  homepage "https://github.com/akshitkrnagpal/revcat"
  version "0.4.0-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.4.0-alpha.1/revcat_0.4.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "3f23a66d72a2138328305d986f3e7c093edd1724e1e52a105052d3c94fee65ea"

      define_method(:install) do
        bin.install "revcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.4.0-alpha.1/revcat_0.4.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "b4cd9add6bfaf75708ce2f4192cc15707d4d25669f81ee3471485ae94a259028"

      define_method(:install) do
        bin.install "revcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.4.0-alpha.1/revcat_0.4.0-alpha.1_linux_amd64.tar.gz"
      sha256 "246219def7434bfdd53c03604cc7896f48a0fddf89e408496e87c7bf5816bae5"
      define_method(:install) do
        bin.install "revcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/revcat/releases/download/v0.4.0-alpha.1/revcat_0.4.0-alpha.1_linux_arm64.tar.gz"
      sha256 "5c31e72d10d2acfd27a846ab22bb628719100b7f8bf7990f593521c1f9083505"
      define_method(:install) do
        bin.install "revcat"
      end
    end
  end

  test do
    system "#{bin}/revcat", "version"
  end
end
