# typed: false
# frozen_string_literal: true

# This file was generated by scripts/release.sh in akshitkrnagpal/tsctl.
# DO NOT EDIT BY HAND - your changes will be overwritten on next release.
class Tsctl < Formula
  desc "Terraform-like CLI for managing Typesense"
  homepage "https://github.com/akshitkrnagpal/tsctl"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.0/tsctl_0.3.0_darwin-x64.tar.gz"
      sha256 "c89567ff1354f0f2e9ed13d8b76b188677667c9d0ce6c91c3a24a63af3a0c25e"
    elsif Hardware::CPU.arm?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.0/tsctl_0.3.0_darwin-arm64.tar.gz"
      sha256 "827a5feaabbdd92864e19157ce6e7d717c6236ec71f6093e7aceb0f0a958f05a"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.0/tsctl_0.3.0_linux-x64.tar.gz"
      sha256 "2bf002c01db4a13f8ef329faf1e97da19fb88bdc0811ff4fca0e2edd8cc7c089"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.0/tsctl_0.3.0_linux-arm64.tar.gz"
      sha256 "97cb3b5160b1e280851583c29a59467d43a8d91c7a22ea6b78ca302648008718"
    end
  end

  def install
    bin.install "tsctl"
  end

  test do
    system "#{bin}/tsctl", "--version"
  end
end
