# typed: false
# frozen_string_literal: true

# This file was generated by scripts/release.sh in akshitkrnagpal/tsctl.
# DO NOT EDIT BY HAND - your changes will be overwritten on next release.
class Tsctl < Formula
  desc "Terraform-like CLI for managing Typesense"
  homepage "https://github.com/akshitkrnagpal/tsctl"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.1/tsctl_0.3.1_darwin-x64.tar.gz"
      sha256 "54345957358244709cd4b9588f4c8a9a59fb6fd8e92537d066eee5a8f58befc5"
    elsif Hardware::CPU.arm?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.1/tsctl_0.3.1_darwin-arm64.tar.gz"
      sha256 "9048a1ff9d525088660dd4d86f1e08ee3580a4911911fee6693d1ee070c78663"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.1/tsctl_0.3.1_linux-x64.tar.gz"
      sha256 "4974692e305593c7584861f2e67dca51a50e1eef78317057bd97bc8f8c81a0fb"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.1/tsctl_0.3.1_linux-arm64.tar.gz"
      sha256 "d04a82560805cbabe0c0a8cf609c13ef4c8d91aacb4194ac761bbc5030366a08"
    end
  end

  def install
    bin.install "tsctl"
  end

  test do
    system "#{bin}/tsctl", "--version"
  end
end
