# typed: false
# frozen_string_literal: true

# This file was generated by scripts/release.sh in akshitkrnagpal/tsctl.
# DO NOT EDIT BY HAND - your changes will be overwritten on next release.
class Tsctl < Formula
  desc "Terraform-like CLI for managing Typesense"
  homepage "https://github.com/akshitkrnagpal/tsctl"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.3/tsctl_0.3.3_darwin-x64.tar.gz"
      sha256 "3fedcb5f824d4ba07db711b4ec9457329fbf18ad7d1c6f7087499c5a5ee02a85"
    elsif Hardware::CPU.arm?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.3/tsctl_0.3.3_darwin-arm64.tar.gz"
      sha256 "1045bfd9444ae31d355ad0afd1885d644f872f4e2acc3bbb0823370261a8ed6b"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.3/tsctl_0.3.3_linux-x64.tar.gz"
      sha256 "288d6a0dce95babbc80c163fbae0a7828d294a20ef15340df7482e0d882e9c97"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshitkrnagpal/tsctl/releases/download/v0.3.3/tsctl_0.3.3_linux-arm64.tar.gz"
      sha256 "276c1e519639ba4c9454f9600bbdc14dc6dd7422d014ca83785b0d02dfd704d6"
    end
  end

  def install
    bin.install "tsctl"
  end

  test do
    system "#{bin}/tsctl", "--version"
  end
end
